name: Package on Update and Push to Main

on:
  push:
    branches:
      - '**'  # 监控所有分支的推送事件
    paths:
      - 'mcdreforged.plugin.json'
      - 'player_ip_logger/**'  # 监控 player_ip_logger 文件夹及其子文件夹

jobs:
  package_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}  # 检出当前推送的分支

    - name: Set up zip
      run: sudo apt-get install zip

    - name: Create mcdr zip package
      run: |
        # Check if the file or folder exists before creating the zip
        if [ -f "mcdreforged.plugin.json" ] || [ -d "player_ip_logger" ]; then
          zip -r player_ip_logger.mcdr mcdreforged.plugin.json player_ip_logger || exit 0
          # List files to confirm the zip file was created
          ls -l
        else
          echo "No relevant files or directories found to package."
        fi

    - name: Push changes to main branch
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        
        # 切换到主线分支
        git fetch origin main
        git checkout main

        # 从当前推送的分支合并到主线
        git merge --no-ff ${{ github.ref_name }} -m "Merge branch '${{ github.ref_name }}' into main"
        
        # 将打包文件和 mcdreforged.plugin.json 推送到主线
        git add player_ip_logger.mcdr mcdreforged.plugin.json
        git commit -m "Update mcdr package and mcdreforged.plugin.json from branch ${{ github.ref_name }}" || echo "No changes to commit"
        
        # 强制推送到主线，覆盖主线内容
        git push origin main --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
